rest_command:
  c5x_wakeup:
    url: "http:///my-psa-car-controller:5000/wakeup/my-vin"
  c5x_set_charging_threshold:
    url: "http://my-psa-car-controller:5000/charge_control?vin=my-vin&percentage={{ states('input_number.c5x_charging_threshold_slider') | int }}"
    method: GET
  c5x_activate_preconditioning:
    url: "http://my-psa-car-controller:5000/preconditioning/my-vin/1"
    method: GET
  c5x_deactivate_preconditioning:
    url: "http://my-psa-car-controller:5000/preconditioning/my-vin/0"
    method: GET

input_button:
  c5x_set_charging_threshold:
    name: Charging Threshold Button
    icon: mdi:battery-charging

input_number:
  c5x_charging_threshold_slider:
    name: Charging Threshold Slider
    initial: 80
    min: 50
    max: 100
    step: 1
    unit_of_measurement: "%"
    icon: mdi:battery-charging