- platform: template
  switches:
    c5x_preconditioning_switch:
      friendly_name: "Preconditioning Switch"
      unique_id: c5x_preconditioning_switch
      icon_template: mdi:thermometer-lines
      availability_template: >-
        {{ states('sensor.c5x_preconditioning_status') != 'Unknown' }}
      value_template: >-
        {{ iif(states('sensor.c5x_preconditioning_status') == 'Enabled', true, false) }}
      turn_on:
        service: rest_command.c5x_activate_preconditioning
      turn_off:
        service: rest_command.c5x_deactivate_preconditioning
