automation:
  # Device Tracker
  - alias: Citroen C5X Position
    description: Create or update Citroen C5X device tracker
    trigger:
      platform: state
      entity_id: sensor.c5x_latitude, sensor.c5x_longitude
    action:
      service: device_tracker.see
      data_template:
        dev_id: c5x_position
        gps:
          - "{{ states('sensor.c5x_latitude') }}"
          - "{{ states('sensor.c5x_longitude') }}"
