# Citroen C5X
- platform: rest
  name: citroen_c5x
  resource: http://my-psa-car-controller:5000/get_vehicleinfo/my-vin?from_cache=1
  scan_interval: 60
  timeout: 30
  value_template: 'OK'
  json_attributes:
   - timed_odometer
   - battery
   - energy
   - environment
   - preconditionning
   - last_position
  unique_id: citroen_c5x

- platform: template
  sensors:
    # Timed Odometer
    c5x_mileage:
      friendly_name: "Mileage"
      unit_of_measurement: "km"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'timed_odometer')['mileage'] }}"
      icon_template: mdi:counter
      device_class: distance
      unique_id: c5x_mileage
    c5x_mileage_update_at:
      friendly_name: "Mileage Updated At"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'timed_odometer')['updated_at'] }}"
      icon_template: mdi:calendar
      device_class: timestamp
      unique_id: c5x_mileage_update_at

    # Battery
    c5x_battery_voltage:
      friendly_name: "Battery Voltage"
      unit_of_measurement: "V"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'battery')['voltage'] * 4 }}"
      icon_template: mdi:flash-triangle-outline
      device_class: voltage
      unique_id: c5x_battery_voltage
    c5x_battery_current:
      friendly_name: "Battery Current"
      unit_of_measurement: "A"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'battery')['current'] }}"
      icon_template: mdi:current-dc
      device_class: current
      unique_id: c5x_battery_current

    # Energy (Battery)
    c5x_battery_level:
      friendly_name: "Battery"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'energy')[0]['level'] }}"
      icon_template: >-
        {% set battery_level = states('sensor.citroen_c5x')|float -%}
        {% if battery_level <= 5 %}
          mdi:battery-outline
        {% elif battery_level > 5 and battery_level <= 25 %}
          mdi:battery-low
        {% elif battery_level > 25 and battery_level <= 65 %}
          mdi:battery-medium
        {% elif battery_level > 65 %}
          mdi:battery-high
        {% endif %}
      device_class: battery
      unique_id: c5x_battery_level
    c5x_battery_autonomy:
      friendly_name: "Battery Autonomy"
      unit_of_measurement: "km"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'energy')[0]['autonomy'] }}"
      icon_template: mdi:map-marker-distance
      device_class: distance
      unique_id: c5x_battery_autonomy
    c5x_battery_health_capacity:
      friendly_name: "Battery Capacity"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'energy')[0]['battery']['health']['capacity'] }}"
      icon_template: mdi:battery-high
      device_class: battery
      unique_id: c5x_battery_health_capacity
    c5x_battery_health_resistance:
      friendly_name: "Battery Resistance"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'energy')[0]['battery']['health']['resistance'] }}"
      icon_template: mdi:resistor
      device_class: battery
      unique_id: c5x_battery_health_resistance
    c5x_charging_status:
      friendly_name: "Charging Status"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'energy')[0]['charging']['status'] }}"
      icon_template: >-
        {% set battery_level = states('sensor.c5x_battery_level')|float -%}
        {% set charging = iif(is_state('switch.c5x_charging_status', 'InProgress'),'-charging', '') -%}
        {% if battery_level <= 5 -%}
          mdi:battery{{charging}}-outline
        {% elif battery_level > 5 and battery_level <= 25 -%}
          mdi:battery-charging-low
        {% elif battery_level > 25 and battery_level <= 65 -%}
          mdi:battery{{charging}}-medium
        {% elif battery_level > 65 -%}
          mdi:battery{{charging}}-high
        {% endif -%}
      unique_id: c5x_charging_status
    c5x_charging_remaining_time:
      friendly_name: "Remaining Time"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'energy')[0]['charging']['remaining_time'] }}"
      icon_template: mdi:clock-time-four-outline
      unique_id: c5x_charging_remaining_time
    c5x_charging_plugged:
      friendly_name: "Plugged"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'energy')[0]['charging']['plugged'] }}"
      icon_template: >-
        mdi:power-plug{{ iif(is_state('switch.c5x_charging_plugged', 'True'),'', '-off') }}-outline
      unique_id: c5x_charging_plugged
    c5x_charging_mode:
      friendly_name: "Charging Mode"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'energy')[0]['charging']['charging_mode'] }}"
      icon_template: >-
          {% if is_state('sensor.c5x_charging_mode', 'Slow') -%}
            mdi:ev-plug-type2
          {% elif is_state('sensor.c5x_charging_mode', 'Quick') -%}
            mdi:ev-plug-ccs2
          {% else -%}
            mdi:power-plug-off-outline
          {% endif -%}
      unique_id: c5x_charging_mode
    c5x_charging_rate:
      friendly_name: "Charging Rate"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'energy')[0]['charging']['charging_rate'] }}"
      unit_of_measurement: "km/h"
      icon_template: mdi:chart-bar
      unique_id: c5x_charging_rate
    c5x_charging_status_updated_at:
      friendly_name: "Charging Status Updated At"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'energy')[0]['updated_at'] }}"
      icon_template: mdi:calendar
      device_class: timestamp
      unique_id: c5x_charging_status_updated_at

    # Energy (Fuel)
    c5x_fuel_autonomy:
      friendly_name: "Fuel Autonomy"
      unit_of_measurement: "km"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'energy')[1]['autonomy'] }}"
      icon_template: mdi:map-marker-distance
      device_class: distance
      unique_id: c5x_fuel_autonomy

    # Environment
    c5x_ambient_temperature:
      friendly_name: "Ambient Temperature"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'environment')['air']['temp'] }}"
      icon_template: mdi:thermometer
      device_class: temperature
      unique_id: c5x_ambient_temperature

    # Preconditioning
    c5x_preconditioning_status:
      friendly_name: "Preconditioning Status"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'preconditionning')['air_conditioning']['status'] }}"
      icon_template: mdi:thermometer-lines
      unique_id: c5x_preconditioning_status

    # Last Position (Coordinates)
    c5x_latitude:
      friendly_name: "Latitude"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'last_position')['geometry']['coordinates'][1] }}"
      icon_template: mdi:latitude
      unique_id: c5x_latitude

    c5x_longitude:
      friendly_name: "Longitude"
      value_template: "{{ state_attr('sensor.citroen_c5x', 'last_position')['geometry']['coordinates'][0] }}"
      icon_template: mdi:longitude
      unique_id: c5x_longitude
