# partial config
switch: !include template_switches.yaml

zha:
  custom_quirks_path: /config/custom_zha_quirks/

recorder:
  purge_keep_days: 15
  db_url: !secret postgres_connection_string
  db_retry_wait: 30
  exclude:
    domains:
      - openplantbook
      - plant
      - sun
      - update
      - remote
      - conversation
      - media_player
      - plant_monitor
      - text
      - image
    entity_globs:
      - sensor.sun*
      - binary_sensor.dev_phone_*
      - binary_sensor.pixel_9_*
      - binary_sensor.2107113sg_*
