# Description: Change entity's brightness in sequence based on the predefined conditions.
# Version: 2023.12.28
alias: Lights Brightness Sequence
sequence:
  - variables:
      entity_id: "{{ entity }}"
      comment: Cycle through predefined brightness states for entity.
  - service: light.turn_on
    target:
      entity_id: "{{ entity }}"
    data:
      brightness: |-
        {% if state_attr(entity_id,'brightness') | int <= 51 %}
          125
        {% elif  state_attr(entity_id,'brightness') | int <= 125 %}
          255
        {% else %}
          50
        {% endif %}
mode: single
icon: mdi:brightness-percent
