# Description: Change entity's brightness.
# Version: 2023.12.28
alias: Lights Brightness
sequence:
  - service: light.turn_on
    target:
      entity_id: "{{ entity }}"
    data:
      brightness: "{{ brightness }}"
mode: single
icon: mdi:brightness-percent
